spring.application.name=shoe-management-backend

server.port=8080
server.servlet.context-path=/api
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5432/shoe_fix
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=StudentPool
jwt.secret=mySuperSecretKeyForJwtThatIsAtLeast32CharactersLong123
jwt.expiration=86400000
ghtk.token=3PVrXGA8gbUa2e28oCbT55SeoImrqLxvbnpZlqx
ghtk.pick-province=H�  Nội
ghtk.pick-district=Sóc Sơn

ghn.base-url=https://dev-online-gateway.ghn.vn/shiip/public-api
ghn.token=7286bc06-4f4e-11f1-a973-aee5264794df
ghn.shop-id=200303
ghn.from-district-id=1677
ghn.from-ward-code=140107
ghn.default-length=30
ghn.default-width=20
ghn.default-height=12
ghn.default-weight-per-shoe=500

vnpay.tmn-code=GPT7Z4F7
vnpay.hash-secret=S7TV92W31MZ65SRWGD62M6CC7IWXCQIC
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/admin/pos/vnpay-return
vnpay.ipn-url=http://localhost:8080/api/v1/pos/vnpay/ipn
vnpay.pos-return-url=http://localhost:5173/admin/pos/vnpay-return
vnpay.online-return-url=http://localhost:5173/checkout/vnpay-return
